# Generated by Django 5.2 on 2025-10-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='photos',
        ),
    ]
