# Generated by Django 5.2 on 2025-10-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mysite.projects', verbose_name='Имя проекта'),
        ),
    ]
