# Generated by Django 5.2 on 2025-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_pages_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='photos',
            field=models.ManyToManyField(related_name='pages', through='mysite.PhotosInPages', through_fields=('page', 'photo'), to='mysite.photos', verbose_name='Фотографии'),
        ),
    ]
