# Generated by Django 5.2 on 2025-10-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_pages_title_alter_pages_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mysite.projects', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mysite.users', verbose_name='Пользователь'),
        ),
    ]
