# Generated by Django 5.2 on 2025-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_pages_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='img',
        ),
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
