# Generated by Django 5.2 on 2025-10-07 19:47

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_pages_img_alter_orders_project_alter_orders_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projects',
            managers=[
                ('inprocess', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('inprocess', 'В процессе'), ('ordered', 'Заказано'), ('archive', 'Архив')], default='inprocess', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['-created'], name='mysite_proj_created_698337_idx'),
        ),
    ]
