# Generated by Django 5.2 on 2025-10-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_orders_user_alter_projects_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.projects', verbose_name='Проект'),
        ),
    ]
