# Generated by Django 5.2 on 2025-10-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_orders_options_remove_orders_total_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='photosinpages',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_page', to='mysite.pages', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='photosinpages',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_pages', to='mysite.photos', verbose_name='Фотография'),
        ),
    ]
